name: local-elasticsearch

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: local-elasticsearch
    environment:
      node.name: local-elasticsearch
      cluster.name: local-es-cluster
      discovery.type: single-node

      # Local dev only
      xpack.security.enabled: "false"
      xpack.security.enrollment.enabled: "false"

      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30
    networks:
      - elastic-network
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    container_name: local-kibana
    environment:
      SERVER_NAME: local-kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

      # Local dev only
      XPACK_SECURITY_ENABLED: "false"
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic-network
    restart: unless-stopped

volumes:
  elasticsearch_data:

networks:
  elastic-network:
    driver: bridge